#TRABALHO

$$\
\begin{align*}
\text{Segunda:} \quad 0.2\text{fr} &+ 0.3\text{fj} + 0.35\text{ar} + 0.15\text{ov} + 0.0\text{sa} = 400 \\
\text{Terça:} \quad 0.3\text{fr} &+ 0.2\text{fj} + 0.15\text{ar} + 0.2\text{ov} + 0.15\text{sa} = 500 \\
\text{Quarta:} \quad 0.25\text{fr} &+ 0.35\text{fj} + 0.2\text{ar} + 0.1\text{ov} + 0.1\text{sa} = 500 \\
\text{Quinta:} \quad 0.4\text{fr} &+ 0.15\text{fj} + 0.3\text{ar} + 0.1\text{ov} + 0.05\text{sa} = 400 \\
\text{Sexta:} \quad 0.2\text{fr} &+ 0.3\text{fj} + 0.15\text{ar} + 0.15\text{ov} + 0.2\text{sa} = 550 \\
\end{align*}
$$


a


A =
\begin{bmatrix}
0.2 & 0.3 & 0.35 & 0.15 & 0.0 \\
0.3 & 0.2 & 0.15 & 0.2 & 0.15 \\
0.25 & 0.35 & 0.2 & 0.1 & 0.1 \\
0.4 & 0.15 & 0.3 & 0.1 & 0.05 \\
0.2 & 0.3 & 0.15 & 0.15 & 0.2 \\
\end{bmatrix}

b =
\begin{bmatrix}
400 & 500 & 500 & 400 & 550 \\
\end{bmatrix}


b =
\begin{bmatrix}
400 \\
500 \\
500 \\
400 \\
550 \\
\end{bmatrix}


LU

In [ ]:
import numpy as np

# Defina o sistema de equações como uma matriz aumentada [A | b]
A = np.array([[0.2, 0.3, 0.35, 0.15, 0.0],
              [0.3, 0.2, 0.15, 0.2, 0.15],
              [0.25, 0.35, 0.2, 0.1, 0.1],
              [0.4, 0.15, 0.3, 0.1, 0.05],
              [0.2, 0.3, 0.15, 0.15, 0.2]], dtype=float)

b = np.array([400, 500, 500, 400, 550], dtype=float)

# Fatoração LU
def lu_decomposition(A):
    n = len(A)
    L = np.eye(n)
    U = A.copy()

    for pivot_row in range(n):
        for row in range(pivot_row + 1, n):
            factor = U[row, pivot_row] / U[pivot_row, pivot_row]
            L[row, pivot_row] = factor
            U[row, pivot_row:] -= factor * U[pivot_row, pivot_row:]

    return L, U

L, U = lu_decomposition(A)

# Resolva Ly = b usando substituição direta (forward substitution)
def forward_substitution(L, b):
    n = len(L)
    y = np.zeros(n)

    for i in range(n):
        y[i] = b[i] - np.sum(L[i, :i] * y[:i])

    return y

# Resolva Ux = y usando substituição reversa (back substitution)
def back_substitution(U, y):
    n = len(U)
    x = np.zeros(n)

    for i in range(n - 1, -1, -1):
        x[i] = (y[i] - np.sum(U[i, i+1:] * x[i+1:])) / U[i, i]

    return x

# Resolva o sistema
y = forward_substitution(L, b)
x = back_substitution(U, y)

print("Solução x por Fatoração LU:")
print(x)

Solução x por Fatoração LU:
[412.5 662.5 162.5 412.5 912.5]


Gaussian

In [ ]:
import numpy as np

# Defina o sistema de equações como uma matriz aumentada [A | b]
A = np.array([[0.2, 0.3, 0.35, 0.15, 0.0],
              [0.3, 0.2, 0.15, 0.2, 0.15],
              [0.25, 0.35, 0.2, 0.1, 0.1],
              [0.4, 0.15, 0.3, 0.1, 0.05],
              [0.2, 0.3, 0.15, 0.15, 0.2]], dtype=float)

b = np.array([400, 500, 500, 400, 550], dtype=float)

# Aplicar eliminação de Gauss para obter uma matriz triangular superior
def gaussian_elimination(A, b):
    n = len(b)

    # Combinação das colunas de A e b em uma matriz aumentada
    Ab = np.column_stack((A, b))

    # Eliminação
    for i in range(n):
        # Encontre o pivô máximo na coluna atual
        pivot_row = np.argmax(np.abs(Ab[i:, i])) + i

        # Troque as linhas se necessário
        Ab[[i, pivot_row]] = Ab[[pivot_row, i]]

        # Faça o pivô igual a 1
        Ab[i] = Ab[i] / Ab[i, i]

        # Elimine as entradas abaixo do pivô
        for j in range(i + 1, n):
            Ab[j] = Ab[j] - Ab[j, i] * Ab[i]

    # Resolva o sistema triangular superior
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = Ab[i, -1] - np.sum(Ab[i, i+1:n] * x[i+1:n])

    return x

# Resolver o sistema
x = gaussian_elimination(A, b)

print("Solução x por Eliminação Gaussiana:")
print(x)

Solução x por Eliminação Gaussiana:
[412.5 662.5 162.5 412.5 912.5]


$$
\begin{align*}
\text{Segunda:} \quad 0.2(412.5) &+ 0.3(662.5) + 0.35(162.5) + 0.15(412.5) + 0.0(912.5) = 400 \\
\text{Terça:} \quad 0.3(412.5) &+ 0.2(662.5) + 0.15(162.5) + 0.2(412.5) + 0.15(912.5) = 500 \\
\text{Quarta:} \quad 0.25(412.5) &+ 0.35(662.5) + 0.2(162.5) + 0.1(412.5) + 0.1(912.5) = 500 \\
\text{Quinta:} \quad 0.4(412.5) &+ 0.15(662.5) + 0.3(162.5) + 0.1(412.5) + 0.05(912.5) = 400 \\
\text{Sexta:} \quad 0.2(412.5) &+ 0.3(662.5) + 0.15(162.5) + 0.15(412.5) + 0.2(912.5) = 550 \\
\end{align*}
$$


$$
\begin{align*}
\text{Segunda:} \quad &+ 82.5 &+ & 198.75 & + & 56.875 & + & 61.875 & + & 0 &= 400\\
\text{Terça:} \quad &+ 123.75 &+ & 132.5 & + & 24.375 & + & 82.5 & + & 136.875 &= 500\\
\text{Quarta:} \quad &+ 103.125 & + & 231.875 & + & 32.5 & + & 41.25 & + & 91.25 &= 500\\
\text{Quinta:} \quad &+ 165 & + & 99.375 & + & 48.75 & + & 41.25 & + & 45.625 &= 400\\
\text{Sexta:} \quad &+ 82.5 & + & 198.75 & + & 24.375 & + & 61.875 & + & 182.5 &= 550\\
\end{align*}
$$


Checando

In [ ]:
import numpy as np

# Define matrix A and vector b (as defined previously)
A = np.array([[0.2, 0.3, 0.35, 0.15, 0.0],
              [0.3, 0.2, 0.15, 0.2, 0.15],
              [0.25, 0.35, 0.2, 0.1, 0.1],
              [0.4, 0.15, 0.3, 0.1, 0.05],
              [0.2, 0.3, 0.15, 0.15, 0.2]], dtype=float)

b = np.array([400, 500, 500, 400, 550], dtype=float)

# Your obtained values from Jacobi (or other methods)
x = np.array([412.5, 662.5, 162.5, 412.5, 912.5])

# Back-substitution
lhs = np.dot(A, x)
print("Computed LHS:", lhs)
print("Difference from RHS:", lhs - b)

# Residual calculation
residual = np.dot(A, x) - b
print("Residual:", residual)
print("Norm of Residual:", np.linalg.norm(residual))

Computed LHS: [400. 500. 500. 400. 550.]
Difference from RHS: [0. 0. 0. 0. 0.]
Residual: [0. 0. 0. 0. 0.]
Norm of Residual: 0.0


# Teste ignorar

In [ ]:
##TESTE

import numpy as np

# Defina o sistema de equações como uma matriz aumentada [A | b]
A = np.array([[0.2, 0.3, 0.35, 0.15, 0.0],
              [0.3, 0.2, 0.15, 0.2, 0.15],
              [0.25, 0.35, 0.2, 0.1, 0.1],
              [0.4, 0.15, 0.3, 0.1, 0.05],
              [0.2, 0.3, 0.15, 0.15, 0.2]], dtype=float)

b = np.array([300, 200, 200, 300, 200], dtype=float)

# Aplicar eliminação de Gauss para obter uma matriz triangular superior
def gaussian_elimination(A, b):
    n = len(b)

    # Combinação das colunas de A e b em uma matriz aumentada
    Ab = np.column_stack((A, b))

    # Eliminação
    for i in range(n):
        # Encontre o pivô máximo na coluna atual
        pivot_row = np.argmax(np.abs(Ab[i:, i])) + i

        # Troque as linhas se necessário
        Ab[[i, pivot_row]] = Ab[[pivot_row, i]]

        # Faça o pivô igual a 1
        Ab[i] = Ab[i] / Ab[i, i]

        # Elimine as entradas abaixo do pivô
        for j in range(i + 1, n):
            Ab[j] = Ab[j] - Ab[j, i] * Ab[i]

    # Resolva o sistema triangular superior
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = Ab[i, -1] - np.sum(Ab[i, i+1:n] * x[i+1:n])

    return x

# Resolver o sistema
x = gaussian_elimination(A, b)

def aa():
  for a in range(450, 1500, 50):
    for b in range(500, 1500, 50):
      for c in range(500, 1500, 50):
        for d in range(400, 1500, 50):
          for e in range(500, 1500, 50):
            o = 0
            for i in gaussian_elimination(A, np.array([a,b,c,d,e], dtype=float)):
              if i <=0: o=1
            if o == 0:
              return [a,b,c,d,e], gaussian_elimination(A, np.array([a,b,c,d,e], dtype=float))

print("Solução x:")
#print(x)
aa()

Solução x:


([450, 500, 500, 400, 550],
 array([263.88888889, 652.77777778, 319.44444444, 597.22222222,
        819.44444444]))

In [ ]:
import numpy as np
import scipy

# Definição da matriz aumentada [A | b]
A = np.array([[0.2, 0.3, 0.35, 0.15, 0.0],
              [0.3, 0.2, 0.15, 0.2, 0.15],
              [0.25, 0.35, 0.2, 0.1, 0.1],
              [0.4, 0.15, 0.3, 0.1, 0.05],
              [0.2, 0.3, 0.15, 0.15, 0.2]], dtype=float)

b = np.array([400, 500, 500, 400, 550], dtype=float)

# Aplicar eliminação de Gauss usando as funções do NumPy
def gaussian_elimination(A, b):
    Ab = np.column_stack((A, b))
    n = len(b)

    for i in range(n):
        pivot_row = np.argmax(np.abs(Ab[i:, i])) + i
        Ab[[i, pivot_row]] = Ab[[pivot_row, i]]
        Ab[i] = Ab[i] / Ab[i, i]
        for j in range(i + 1, n):
            Ab[j] = Ab[j] - Ab[j, i] * Ab[i]

    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = Ab[i, -1] - np.sum(Ab[i, i+1:n] * x[i+1:n])

    return x

# Resolver o sistema usando a Eliminação Gaussiana com as funções do NumPy
x_gauss = gaussian_elimination(A, b)

print("Solução x por Eliminação Gaussiana (com NumPy):")
print(x_gauss)

# Fatorização LU usando as funções do NumPy
P, L, U = scipy.linalg.lu(A)
y = scipy.linalg.solve_triangular(L, P @ b, lower=True)
x_lu = scipy.linalg.solve_triangular(U, y)

print("\nSolução x por Fatorização LU (com NumPy):")
print(x_lu)


Solução x por Eliminação Gaussiana (com NumPy):
[412.5 662.5 162.5 412.5 912.5]

Solução x por Fatorização LU (com NumPy):
[-429.16666667 -345.83333333 2154.16666667 -429.16666667 2404.16666667]
